use std::{
    error::Error as StdError,
    fmt,
    io::{self, Read, Seek},
};

use cap_std::fs::Dir;
use thiserror::Error;

use crate::{ArtifactId, ArtifactRecord, ArtifactRecordError, ProjectError, StoreId};

mod coordination;
mod publication;
mod recovery;
mod verification;

#[cfg(test)]
mod tests;

const STAGING_DIRECTORY: &str = ".marklab-staging";
const QUARANTINE_DIRECTORY: &str = ".marklab-quarantine";
const OBJECT_DIRECTORY: &str = "objects/sha256";
const COORDINATION_FILE: &str = ".marklab-store.lock";
const STREAM_BUFFER_BYTES: usize = 64 * 1024;

/// Scoped reader surface for one verified artifact descriptor.
pub trait ArtifactReadSeek: Read + Seek + Send {}

impl<T: Read + Seek + Send> ArtifactReadSeek for T {}

#[derive(Clone, Copy, Eq, PartialEq)]
enum PublishFault {
    None,
    #[cfg(test)]
    AfterFileSync,
    #[cfg(test)]
    AfterPublication,
    #[cfg(test)]
    StagingCreateCollision,
}

#[derive(Clone, Copy, Eq, PartialEq)]
enum RecoveryFault {
    None,
    #[cfg(test)]
    AfterQuarantineLink,
    #[cfg(test)]
    AfterQuarantineSync,
    #[cfg(test)]
    AfterStagingRemove,
}

/// Capability-confined local binding for immutable artifact objects.
pub struct LocalArtifactStore {
    root: Dir,
    store_id: StoreId,
}

/// Outcome of an immutable managed publication attempt.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum PublicationDisposition {
    /// This caller atomically created the final hard link.
    Created,
    /// Matching content was already present or won a concurrent race.
    AlreadyPresent,
}

/// Published record with its managed local replica declaration.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ArtifactPublication {
    record: ArtifactRecord,
    disposition: PublicationDisposition,
}

impl ArtifactPublication {
    /// Record augmented with the managed locator for this store.
    pub fn record(&self) -> &ArtifactRecord {
        &self.record
    }

    /// Whether this caller created or reused the immutable object.
    pub fn disposition(&self) -> PublicationDisposition {
        self.disposition
    }

    /// Consume the publication and return the augmented record.
    pub fn into_record(self) -> ArtifactRecord {
        self.record
    }
}

/// Report from conservative staging recovery.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RecoveryReport {
    quarantined: Vec<String>,
    issues: Vec<RecoveryIssue>,
}

impl RecoveryReport {
    /// Recognized regular entries moved to quarantine, in deterministic order.
    pub fn quarantined(&self) -> &[String] {
        &self.quarantined
    }

    /// Entries retained or partially handled for explicit operator review.
    pub fn issues(&self) -> &[RecoveryIssue] {
        &self.issues
    }
}

/// One staging entry that recovery deliberately did not silently delete.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RecoveryIssue {
    entry: String,
    quarantine_target: Option<String>,
    reason: RecoveryIssueReason,
}

impl RecoveryIssue {
    /// Entry name, lossily rendered only when the filesystem name is not UTF-8.
    pub fn entry(&self) -> &str {
        &self.entry
    }

    /// Quarantine target already created before a partial recovery failure.
    pub fn quarantine_target(&self) -> Option<&str> {
        self.quarantine_target.as_deref()
    }

    /// Why the entry requires operator attention.
    pub fn reason(&self) -> &RecoveryIssueReason {
        &self.reason
    }
}

/// Conservative reason an abandoned entry was retained or needs review.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum RecoveryIssueReason {
    /// Filesystem entry name is not UTF-8.
    NonUtf8Name,
    /// Entry name was not generated by this store implementation.
    UnrecognizedName,
    /// Entry is a symlink, directory, FIFO, socket, device, or other non-regular type.
    NonRegularFile,
    /// A capability-relative filesystem operation failed.
    Io(String),
}

/// Failure from the verified store boundary or its scoped reader callback.
#[derive(Debug)]
pub enum VerifiedReaderError<E> {
    /// Opening, pre-verifying, seeking, or post-verifying the managed artifact failed.
    Store(ArtifactStoreError),
    /// The caller rejected otherwise verified artifact bytes.
    Callback(E),
}

impl<E: fmt::Display> fmt::Display for VerifiedReaderError<E> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Store(error) => error.fmt(formatter),
            Self::Callback(error) => {
                write!(formatter, "verified artifact callback failed: {error}")
            }
        }
    }
}

impl<E: StdError + 'static> StdError for VerifiedReaderError<E> {
    fn source(&self) -> Option<&(dyn StdError + 'static)> {
        match self {
            Self::Store(error) => Some(error),
            Self::Callback(error) => Some(error),
        }
    }
}

/// Capability, availability, integrity, publication, and recovery failures.
#[derive(Debug, Error)]
pub enum ArtifactStoreError {
    /// Ambient store-root inspection/opening failed.
    #[error("failed to {operation} local artifact store root: {source}")]
    Root {
        /// Failed operation.
        operation: &'static str,
        /// Filesystem error.
        #[source]
        source: io::Error,
    },
    /// An observed root, intermediate component, or leaf is a symlink.
    #[error("artifact path crosses a symlink boundary at {key:?}")]
    SymlinkBoundary {
        /// Store-relative component or root marker.
        key: String,
    },
    /// An object expected to be a directory/regular file has another type.
    #[error("artifact path has an unsupported file type at {key:?}")]
    UnsupportedFileType {
        /// Store-relative component or root marker.
        key: String,
    },
    /// A record has no replica bound to this store.
    #[error("artifact {artifact} has no locator for store {store_id:?}")]
    LocatorNotFound {
        /// Affected artifact.
        artifact: ArtifactId,
        /// Required store.
        store_id: StoreId,
    },
    /// Explicit locator is bound to another store.
    #[error("artifact locator uses store {observed:?}, expected {expected:?}")]
    WrongStore {
        /// Required store.
        expected: StoreId,
        /// Locator store.
        observed: StoreId,
    },
    /// Referenced regular object is absent.
    #[error("artifact {artifact} is missing at store key {key:?}")]
    MissingObject {
        /// Affected artifact.
        artifact: ArtifactId,
        /// Missing relative key.
        key: String,
    },
    /// Streamed bytes differ in digest or length.
    #[error("artifact {artifact} failed content verification: {source}")]
    ContentIntegrity {
        /// Affected artifact.
        artifact: ArtifactId,
        /// Exact digest/length mismatch.
        #[source]
        source: Box<ProjectError>,
    },
    /// Existing managed target is not the expected immutable content.
    #[error("managed target for artifact {artifact} contains conflicting content")]
    ImmutableConflict {
        /// Conflicting artifact target.
        artifact: ArtifactId,
    },
    /// Caller-supplied streaming writer failed before publication.
    #[error("artifact write callback failed: {source}")]
    WriteCallback {
        /// Callback I/O error.
        #[source]
        source: io::Error,
    },
    /// Final object was published, but a subsequent durability/cleanup step failed.
    #[error("artifact {artifact} was published but failed to {operation}: {source}")]
    PublishedButCleanupFailed {
        /// Published artifact.
        artifact: ArtifactId,
        /// Failed post-publication operation.
        operation: &'static str,
        /// Filesystem error.
        #[source]
        source: io::Error,
    },
    /// Capability-relative filesystem operation failed.
    #[error("failed to {operation} at store key {key:?}: {source}")]
    Io {
        /// Failed operation.
        operation: &'static str,
        /// Store-relative key.
        key: String,
        /// Filesystem error.
        #[source]
        source: io::Error,
    },
    /// Managed record cannot add this store locator without conflict.
    #[error(transparent)]
    InvalidRecord(#[from] ArtifactRecordError),
    /// Unique staging names repeatedly collided.
    #[error("could not allocate a unique artifact staging name")]
    StagingNameExhausted,
}
