use super::*;

pub(super) fn run_cli() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        #[cfg(feature = "wsi")]
        Commands::InspectSlide { slide, output } => slide::inspect(slide, output),
        #[cfg(feature = "wsi")]
        Commands::ExtractRegion {
            slide,
            scene,
            series,
            level,
            z,
            c,
            t,
            x,
            y,
            width,
            height,
            output,
            force,
        } => slide::extract(slide::ExtractRequest {
            slide,
            region: crate::RegionRequest {
                scene,
                series,
                level,
                plane: crate::PlaneSelection { z, c, t },
                x,
                y,
                width,
                height,
            },
            output,
            force,
        }),
        Commands::Analyze {
            cells,
            mask,
            config,
            out,
            threads,
            log,
            trace_json,
            timings,
            heap_profile,
        } => analyze::run(AnalyzeRequest {
            cells,
            mask,
            config,
            out,
            threads,
            observability: ObservabilityOptions {
                log,
                trace_json,
                timings,
            },
            heap_profile,
        }),
        Commands::Classical {
            cells,
            mask,
            out,
            r_max_um,
            r_steps,
            simulations,
            seed,
            alpha,
            memory_budget_mib,
            max_pair_visits,
            max_csr_draws,
        } => classical::run(ClassicalRequest {
            cells,
            mask,
            out,
            r_max_um,
            r_steps,
            simulations,
            seed,
            alpha,
            memory_budget_mib,
            maximum_pair_visits: max_pair_visits,
            maximum_csr_draws: max_csr_draws,
        }),
        Commands::NearestSpace {
            cells,
            mask,
            out,
            r_max_um,
            r_steps,
            probe_grid_x,
            probe_grid_y,
            simulations,
            seed,
            alpha,
            j_denominator_epsilon,
            memory_budget_mib,
            max_nearest_queries,
            max_csr_draws,
        } => nearest_space::run(NearestSpaceRequest {
            cells,
            mask,
            out,
            r_max_um,
            r_steps,
            probe_grid_x,
            probe_grid_y,
            simulations,
            seed,
            alpha,
            j_denominator_epsilon,
            memory_budget_mib,
            maximum_nearest_queries: max_nearest_queries,
            maximum_csr_draws: max_csr_draws,
        }),
        Commands::Project { command } => match command {
            ProjectCommands::CategoricalPair {
                project,
                cells,
                mask,
                out,
                source_level,
                target_level,
                radii_um,
                permutations,
                seed,
                alpha,
                memory_budget_mib,
                max_pair_visits,
                max_null_pair_evaluations,
            } => categorical_pair::run_project(categorical_pair::Request {
                project,
                cells,
                mask,
                out,
                source_level,
                target_level,
                radii_um,
                permutations,
                seed,
                alpha,
                memory_budget_mib,
                maximum_pair_visits: max_pair_visits,
                maximum_null_pair_evaluations: max_null_pair_evaluations,
            }),
            ProjectCommands::CategoricalCrossPairCorrelation {
                project,
                cells,
                mask,
                out,
                source_level,
                target_level,
                radii_um,
                bandwidth_um,
                permutations,
                seed,
                alpha,
                memory_budget_mib,
                max_pair_visits,
                max_null_pair_evaluations,
            } => categorical_cross_pair_correlation::run_project(
                categorical_cross_pair_correlation::Request {
                    project,
                    cells,
                    mask,
                    out,
                    source_level,
                    target_level,
                    radii_um,
                    bandwidth_um,
                    permutations,
                    seed,
                    alpha,
                    memory_budget_mib,
                    maximum_pair_visits: max_pair_visits,
                    maximum_null_pair_evaluations: max_null_pair_evaluations,
                },
            ),
            ProjectCommands::TranslationCategoricalCrossPairCorrelation {
                project,
                cells,
                mask,
                out,
                source_level,
                target_level,
                radii_um,
                bandwidth_um,
                permutations,
                seed,
                alpha,
                memory_budget_mib,
                max_pair_visits,
                max_null_pair_evaluations,
                max_overlap_evaluations,
                max_overlap_candidate_work,
                max_overlap_output_vertices,
            } => categorical_cross_pair_correlation::run_translation_project(
                categorical_cross_pair_correlation::TranslationRequest {
                    base: categorical_cross_pair_correlation::Request {
                        project,
                        cells,
                        mask,
                        out,
                        source_level,
                        target_level,
                        radii_um,
                        bandwidth_um,
                        permutations,
                        seed,
                        alpha,
                        memory_budget_mib,
                        maximum_pair_visits: max_pair_visits,
                        maximum_null_pair_evaluations: max_null_pair_evaluations,
                    },
                    maximum_overlap_evaluations: max_overlap_evaluations,
                    maximum_overlap_candidate_work: max_overlap_candidate_work,
                    maximum_overlap_output_vertices: max_overlap_output_vertices,
                },
            ),
            ProjectCommands::IsotropicCategoricalCrossPairCorrelation {
                project,
                cells,
                mask,
                out,
                source_level,
                target_level,
                radii_um,
                bandwidth_um,
                permutations,
                seed,
                alpha,
                memory_budget_mib,
                max_pair_visits,
                max_null_pair_evaluations,
                max_visible_arc_evaluations,
                max_arc_segment_tests,
                max_arc_membership_queries,
            } => categorical_cross_pair_correlation::run_isotropic_project(
                categorical_cross_pair_correlation::IsotropicRequest {
                    base: categorical_cross_pair_correlation::Request {
                        project,
                        cells,
                        mask,
                        out,
                        source_level,
                        target_level,
                        radii_um,
                        bandwidth_um,
                        permutations,
                        seed,
                        alpha,
                        memory_budget_mib,
                        maximum_pair_visits: max_pair_visits,
                        maximum_null_pair_evaluations: max_null_pair_evaluations,
                    },
                    maximum_visible_arc_evaluations: max_visible_arc_evaluations,
                    maximum_arc_segment_tests: max_arc_segment_tests,
                    maximum_arc_membership_queries: max_arc_membership_queries,
                },
            ),
            ProjectCommands::InhomogeneousSpatial {
                project,
                cells,
                mask,
                out,
                radii_um,
                bandwidth_um,
                cross_fit_folds,
                grid_x,
                grid_y,
                simulations,
                seed,
                alpha,
                minimum_intensity_per_um2,
                memory_budget_mib,
                max_probes,
                max_intensity_evaluations,
                max_pair_visits,
                max_null_draws,
            } => inhomogeneous_spatial::run_project(inhomogeneous_spatial::Request {
                project,
                cells,
                mask,
                out,
                radii_um,
                bandwidth_um,
                cross_fit_folds,
                integration_grid: [grid_x, grid_y],
                simulations,
                seed,
                alpha,
                minimum_intensity_per_um2,
                memory_budget_mib,
                maximum_probes: max_probes,
                maximum_intensity_evaluations: max_intensity_evaluations,
                maximum_pair_visits: max_pair_visits,
                maximum_null_draws: max_null_draws,
            }),
            ProjectCommands::TranslationSpatial {
                project,
                cells,
                mask,
                out,
                radii_um,
                simulations,
                seed,
                alpha,
                memory_budget_mib,
                max_pair_visits,
                max_overlap_evaluations,
                max_overlap_candidate_work,
                max_overlap_output_vertices,
                max_csr_draws,
            } => translation_spatial::run_project(translation_spatial::Request {
                project,
                cells,
                mask,
                out,
                radii_um,
                simulations,
                seed,
                alpha,
                memory_budget_mib,
                maximum_pair_visits: max_pair_visits,
                maximum_overlap_evaluations: max_overlap_evaluations,
                maximum_overlap_candidate_work: max_overlap_candidate_work,
                maximum_overlap_output_vertices: max_overlap_output_vertices,
                maximum_csr_draws: max_csr_draws,
            }),
            ProjectCommands::TranslationPairCorrelation {
                project,
                cells,
                mask,
                out,
                radii_um,
                bandwidth_um,
                simulations,
                seed,
                alpha,
                memory_budget_mib,
                max_pair_visits,
                max_overlap_evaluations,
                max_overlap_candidate_work,
                max_overlap_output_vertices,
                max_csr_draws,
            } => translation_pair_correlation::run_project(translation_pair_correlation::Request {
                project,
                cells,
                mask,
                out,
                radii_um,
                bandwidth_um,
                simulations,
                seed,
                alpha,
                memory_budget_mib,
                maximum_pair_visits: max_pair_visits,
                maximum_overlap_evaluations: max_overlap_evaluations,
                maximum_overlap_candidate_work: max_overlap_candidate_work,
                maximum_overlap_output_vertices: max_overlap_output_vertices,
                maximum_csr_draws: max_csr_draws,
            }),
            ProjectCommands::IsotropicSpatial {
                project,
                cells,
                mask,
                out,
                radii_um,
                simulations,
                seed,
                alpha,
                memory_budget_mib,
                max_pair_visits,
                max_visible_arc_evaluations,
                max_arc_segment_tests,
                max_arc_membership_queries,
                max_csr_draws,
            } => isotropic_spatial::run_project(isotropic_spatial::Request {
                project,
                cells,
                mask,
                out,
                radii_um,
                simulations,
                seed,
                alpha,
                memory_budget_mib,
                maximum_pair_visits: max_pair_visits,
                maximum_visible_arc_evaluations: max_visible_arc_evaluations,
                maximum_arc_segment_tests: max_arc_segment_tests,
                maximum_arc_membership_queries: max_arc_membership_queries,
                maximum_csr_draws: max_csr_draws,
            }),
            ProjectCommands::IsotropicPairCorrelation {
                project,
                cells,
                mask,
                out,
                radii_um,
                bandwidth_um,
                simulations,
                seed,
                alpha,
                memory_budget_mib,
                max_pair_visits,
                max_visible_arc_evaluations,
                max_arc_segment_tests,
                max_arc_membership_queries,
                max_csr_draws,
            } => isotropic_pair_correlation::run_project(isotropic_pair_correlation::Request {
                project,
                cells,
                mask,
                out,
                radii_um,
                bandwidth_um,
                simulations,
                seed,
                alpha,
                memory_budget_mib,
                maximum_pair_visits: max_pair_visits,
                maximum_visible_arc_evaluations: max_visible_arc_evaluations,
                maximum_arc_segment_tests: max_arc_segment_tests,
                maximum_arc_membership_queries: max_arc_membership_queries,
                maximum_csr_draws: max_csr_draws,
            }),
            ProjectCommands::GaussianBandwidthSelectedSpatial {
                project,
                cells,
                mask,
                out,
                radii_um,
                candidate_bandwidths_um,
                grid_x,
                grid_y,
                simulations,
                seed,
                alpha,
                minimum_intensity_per_um2,
                memory_budget_mib,
                max_probes,
                max_intensity_evaluations,
                max_pair_visits,
                max_null_draws,
                max_bandwidth_candidates,
                max_selection_intensity_evaluations,
            } => inhomogeneous_bandwidth_selection::run_project(
                inhomogeneous_bandwidth_selection::Request {
                    project,
                    cells,
                    mask,
                    out,
                    radii_um,
                    candidate_bandwidths_um,
                    integration_grid: [grid_x, grid_y],
                    simulations,
                    seed,
                    alpha,
                    minimum_intensity_per_um2,
                    memory_budget_mib,
                    maximum_probes: max_probes,
                    maximum_intensity_evaluations: max_intensity_evaluations,
                    maximum_pair_visits: max_pair_visits,
                    maximum_null_draws: max_null_draws,
                    maximum_bandwidth_candidates: max_bandwidth_candidates,
                    maximum_selection_intensity_evaluations: max_selection_intensity_evaluations,
                },
            ),
            ProjectCommands::PiecewiseCompartmentSpatial {
                project,
                cells,
                observation_mask,
                negative_mask,
                positive_mask,
                negative_compartment_id,
                positive_compartment_id,
                out,
                radii_um,
                simulations,
                seed,
                alpha,
                memory_budget_mib,
                max_boundary_segments,
                max_compartment_queries,
                max_pair_visits,
                max_null_draws,
            } => {
                piecewise_compartment_spatial::run_project(piecewise_compartment_spatial::Request {
                    project,
                    cells,
                    observation_mask,
                    negative_mask,
                    positive_mask,
                    negative_compartment_id,
                    positive_compartment_id,
                    out,
                    radii_um,
                    simulations,
                    seed,
                    alpha,
                    memory_budget_mib,
                    maximum_boundary_segments: max_boundary_segments,
                    maximum_compartment_queries: max_compartment_queries,
                    maximum_pair_visits: max_pair_visits,
                    maximum_null_draws: max_null_draws,
                })
            }
            ProjectCommands::PiecewiseCompartmentPairCorrelation {
                project,
                cells,
                observation_mask,
                negative_mask,
                positive_mask,
                negative_compartment_id,
                positive_compartment_id,
                out,
                radii_um,
                pair_bandwidth_um,
                simulations,
                seed,
                alpha,
                memory_budget_mib,
                max_boundary_segments,
                max_compartment_queries,
                max_pair_visits,
                max_null_draws,
            } => piecewise_compartment_pair_correlation::run_project(
                piecewise_compartment_pair_correlation::Request {
                    project,
                    cells,
                    observation_mask,
                    negative_mask,
                    positive_mask,
                    negative_compartment_id,
                    positive_compartment_id,
                    out,
                    radii_um,
                    pair_bandwidth_um,
                    simulations,
                    seed,
                    alpha,
                    memory_budget_mib,
                    maximum_boundary_segments: max_boundary_segments,
                    maximum_compartment_queries: max_compartment_queries,
                    maximum_pair_visits: max_pair_visits,
                    maximum_null_draws: max_null_draws,
                },
            ),
            ProjectCommands::InhomogeneousPairCorrelation {
                project,
                cells,
                mask,
                out,
                radii_um,
                intensity_bandwidth_um,
                pair_bandwidth_um,
                grid_x,
                grid_y,
                simulations,
                seed,
                alpha,
                minimum_intensity_per_um2,
                memory_budget_mib,
                max_probes,
                max_intensity_evaluations,
                max_pair_visits,
                max_null_draws,
            } => inhomogeneous_pair_correlation::run_project(
                inhomogeneous_pair_correlation::Request {
                    project,
                    cells,
                    mask,
                    out,
                    radii_um,
                    intensity_bandwidth_um,
                    pair_bandwidth_um,
                    integration_grid: [grid_x, grid_y],
                    simulations,
                    seed,
                    alpha,
                    minimum_intensity_per_um2,
                    memory_budget_mib,
                    maximum_probes: max_probes,
                    maximum_intensity_evaluations: max_intensity_evaluations,
                    maximum_pair_visits: max_pair_visits,
                    maximum_null_draws: max_null_draws,
                },
            ),
            ProjectCommands::InhomogeneousCategoricalCrossPairCorrelation {
                project,
                cells,
                mask,
                out,
                source_level,
                target_level,
                radii_um,
                intensity_bandwidth_um,
                cross_fit_folds,
                edge_correction,
                pair_bandwidth_um,
                grid_x,
                grid_y,
                simulations,
                seed,
                alpha,
                minimum_intensity_per_um2,
                memory_budget_mib,
                max_probes,
                max_intensity_evaluations,
                max_pair_visits,
                max_null_draws,
                max_overlap_evaluations,
                max_overlap_candidate_work,
                max_overlap_output_vertices,
                max_visible_arc_evaluations,
                max_arc_segment_tests,
                max_arc_membership_queries,
            } => {
                let required = |value: Option<usize>, name: &str| {
                    value.ok_or_else(|| {
                        crate::MarklabError::Validation(format!(
                            "--{name} is required by the selected inhomogeneous edge correction"
                        ))
                    })
                };
                let edge_correction = match edge_correction {
                    CliInhomogeneousCrossEdgeCorrection::StandardBorder => {
                        inhomogeneous_categorical_cross_pair_correlation::EdgeCorrectionRequest::StandardBorder
                    }
                    CliInhomogeneousCrossEdgeCorrection::Translation => {
                        inhomogeneous_categorical_cross_pair_correlation::EdgeCorrectionRequest::Translation {
                            maximum_overlap_evaluations: required(max_overlap_evaluations, "max-overlap-evaluations")?,
                            maximum_overlap_candidate_work: required(max_overlap_candidate_work, "max-overlap-candidate-work")?,
                            maximum_overlap_output_vertices: required(max_overlap_output_vertices, "max-overlap-output-vertices")?,
                        }
                    }
                    CliInhomogeneousCrossEdgeCorrection::Isotropic => {
                        inhomogeneous_categorical_cross_pair_correlation::EdgeCorrectionRequest::Isotropic {
                            maximum_visible_arc_evaluations: required(max_visible_arc_evaluations, "max-visible-arc-evaluations")?,
                            maximum_arc_segment_tests: required(max_arc_segment_tests, "max-arc-segment-tests")?,
                            maximum_arc_membership_queries: required(max_arc_membership_queries, "max-arc-membership-queries")?,
                        }
                    }
                };
                inhomogeneous_categorical_cross_pair_correlation::run_project(
                    inhomogeneous_categorical_cross_pair_correlation::Request {
                        project,
                        cells,
                        mask,
                        out,
                        source_level,
                        target_level,
                        radii_um,
                        intensity_bandwidth_um,
                        cross_fit_folds,
                        pair_bandwidth_um,
                        integration_grid: [grid_x, grid_y],
                        simulations,
                        seed,
                        alpha,
                        minimum_intensity_per_um2,
                        memory_budget_mib,
                        maximum_probes: max_probes,
                        maximum_intensity_evaluations: max_intensity_evaluations,
                        maximum_pair_visits: max_pair_visits,
                        maximum_null_draws: max_null_draws,
                        edge_correction,
                    },
                )
            }
            ProjectCommands::ScalarVariogram {
                project,
                cells,
                mask,
                out,
                lag_edges_um,
                condition_by_histologic_compartment,
                permutations,
                seed,
                alpha,
                memory_budget_mib,
                max_pair_visits,
                max_permutation_pair_evaluations,
            } => scalar_variogram::run_project(scalar_variogram::Request {
                project,
                cells,
                mask,
                out,
                lag_edges_um,
                condition_by_histologic_compartment,
                permutations,
                seed,
                alpha,
                memory_budget_mib,
                maximum_pair_visits: max_pair_visits,
                maximum_permutation_pair_evaluations: max_permutation_pair_evaluations,
            }),
            ProjectCommands::Classical {
                project,
                cells,
                mask,
                out,
                r_max_um,
                r_steps,
                simulations,
                seed,
                alpha,
                memory_budget_mib,
                max_pair_visits,
                max_csr_draws,
            } => classical::run_project(
                project,
                ClassicalRequest {
                    cells,
                    mask,
                    out,
                    r_max_um,
                    r_steps,
                    simulations,
                    seed,
                    alpha,
                    memory_budget_mib,
                    maximum_pair_visits: max_pair_visits,
                    maximum_csr_draws: max_csr_draws,
                },
            ),
            ProjectCommands::NearestSpace {
                project,
                cells,
                mask,
                out,
                r_max_um,
                r_steps,
                probe_grid_x,
                probe_grid_y,
                simulations,
                seed,
                alpha,
                j_denominator_epsilon,
                memory_budget_mib,
                max_nearest_queries,
                max_csr_draws,
            } => nearest_space::run_project(
                project,
                NearestSpaceRequest {
                    cells,
                    mask,
                    out,
                    r_max_um,
                    r_steps,
                    probe_grid_x,
                    probe_grid_y,
                    simulations,
                    seed,
                    alpha,
                    j_denominator_epsilon,
                    memory_budget_mib,
                    maximum_nearest_queries: max_nearest_queries,
                    maximum_csr_draws: max_csr_draws,
                },
            ),
        },
        Commands::Batch {
            manifest,
            config,
            out,
            threads,
        } => batch::run(manifest, config, out, threads),
        Commands::Prepost { pre, post, out } => prepost::run(pre, post, out),
        Commands::ProfilePlan { workload, out } => profile::run(&workload, out),
        Commands::Simulate { command } => match command {
            SimulateCommands::RandomLabeling { n, p, seed, out } => simulate::run(n, p, seed, out),
            SimulateCommands::GrowthFront {
                input,
                diffusion_um2_per_time,
                growth_rate_per_time,
                carrying_capacity,
                final_time,
                time_step,
                front_threshold_fraction,
                record_every_steps,
                maximum_cell_steps,
                out,
            } => simulate::growth_front::run(
                input,
                diffusion_um2_per_time,
                growth_rate_per_time,
                carrying_capacity,
                final_time,
                time_step,
                front_threshold_fraction,
                record_every_steps,
                maximum_cell_steps,
                out,
            ),
            SimulateCommands::SpatialCompetition {
                input,
                diffusion_a_um2_per_time,
                diffusion_b_um2_per_time,
                growth_a_per_time,
                growth_b_per_time,
                carrying_a,
                carrying_b,
                competition_a_from_b,
                competition_b_from_a,
                treatment_a_per_time,
                treatment_b_per_time,
                final_time,
                time_step,
                extinction_threshold_fraction,
                record_every_steps,
                maximum_cell_species_steps,
                out,
            } => simulate::spatial_competition::run(
                input,
                diffusion_a_um2_per_time,
                diffusion_b_um2_per_time,
                growth_a_per_time,
                growth_b_per_time,
                carrying_a,
                carrying_b,
                competition_a_from_b,
                competition_b_from_a,
                treatment_a_per_time,
                treatment_b_per_time,
                final_time,
                time_step,
                extinction_threshold_fraction,
                record_every_steps,
                maximum_cell_species_steps,
                out,
            ),
            SimulateCommands::AgentCompetition {
                input,
                seed,
                maximum_events,
                maximum_agents,
                maximum_pair_visits,
                retain_events,
                out,
            } => simulate::agent_competition::run(
                input,
                seed,
                maximum_events,
                maximum_agents,
                maximum_pair_visits,
                retain_events,
                out,
            ),
            SimulateCommands::ReactionDiffusion {
                input,
                final_time,
                time_step,
                record_every_steps,
                maximum_cell_steps,
                out,
            } => simulate::reaction_diffusion::run(
                input,
                final_time,
                time_step,
                record_every_steps,
                maximum_cell_steps,
                out,
            ),
            SimulateCommands::EvolveInterface {
                input,
                final_time,
                time_step,
                reinitialize_every_steps,
                record_every_steps,
                maximum_cell_steps,
                maximum_reinitialization_distance_visits,
                out,
            } => simulate::level_set::run(
                input,
                final_time,
                time_step,
                reinitialize_every_steps,
                record_every_steps,
                maximum_cell_steps,
                maximum_reinitialization_distance_visits,
                out,
            ),
            SimulateCommands::VascularTransport {
                input,
                final_time,
                time_step,
                hypoxia_threshold,
                record_every_steps,
                maximum_cell_steps,
                out,
            } => simulate::vascular_transport::run(
                input,
                final_time,
                time_step,
                hypoxia_threshold,
                record_every_steps,
                maximum_cell_steps,
                out,
            ),
            SimulateCommands::MechanisticTissue { input, out } => {
                simulate::mechanistic_tissue::run(input, out)
            }
            SimulateCommands::SummaryMatching { input, out } => {
                simulate::summary_matching::run(input, out)
            }
        },
        Commands::Multimodal { command } => match command {
            MultimodalCommands::Analyze {
                he_cells,
                ihc_cells,
                landmarks,
                config,
                out,
                case_id,
                timepoint,
                protein,
                he_format,
                cellvit_min_probability,
            } => multimodal::analyze::run(MultimodalAnalyzeRequest {
                he_cells,
                ihc_cells,
                landmarks,
                config,
                out,
                case_id,
                timepoint,
                protein,
                he_format,
                cellvit_min_probability,
            }),
            MultimodalCommands::Prepost { pre, post, out } => {
                multimodal::commands::prepost(pre, post, out)
            }
            MultimodalCommands::Batch { manifest, out } => {
                multimodal::commands::batch(manifest, out)
            }
        },
        Commands::Smoke {
            suite,
            replicates,
            out,
        } => smoke::run(&suite, replicates, out),
    }
}
