[package]
name = "mmrspace-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
tempfile = "3"
mmrspace = { path = "..", default-features = false, features = ["csv"] }

[[bin]]
name = "config"
path = "fuzz_targets/config.rs"
test = false
doc = false
bench = false

[[bin]]
name = "geojson_mask"
path = "fuzz_targets/mask_contains.rs"
test = false
doc = false
bench = false

[[bin]]
name = "csv_row_parser"
path = "fuzz_targets/load_cells.rs"
test = false
doc = false
bench = false
